=== portoman/DAW_Github/04_Lenguaje de marcas/PreviaExamen2/public_html/rede_enunciado.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <xs:element name="Red">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Fecha" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="Maquina" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
 
    <!--FECHA-->
    <xs:element name="Fecha" type="xs:string"/>
 
    <!--MAQUINA-->
    <xs:element name="Maquina">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Info" minOccurs="0" maxOccurs="unbounded"/> 
                <xs:element ref="Config" minOccurs="0" maxOccurs="unbounded"/> 
                <xs:element ref="Notas" minOccurs="0" maxOccurs="unbounded"/> 
            </xs:sequence>
            <xs:attribute name="Nombre" type="codNombre"/>
        </xs:complexType>
    </xs:element>
  
    <xs:simpleType name="codNombre">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z]{0,10}|[A-Za-z]{0,7}[0-9]{0,3}"/>
        </xs:restriction>
    </xs:simpleType>
  
    <xs:element name="Info">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Tipo" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="Fabricante" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="Procesador" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="Memoria" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="Disco" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="Grabadora" minOccurs="0" maxOccurs="1"/>
                <xs:group ref="GrupoTiposSoportes" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Procesador">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="Marca" type="xs:string"/>
                    <xs:attribute name="Velocidad" type="xs:string"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
  
    <xs:element name="Disco">
        <xs:complexType>
            <xs:attribute name="Tecnologia" type="xs:string"/>
            <xs:attribute name="Capacidad" type="xs:string"/>
        </xs:complexType>
    </xs:element>
  
    <xs:group name="GrupoTiposSoportes">
        <xs:choice>
            <xs:element ref="Lectora"/>
            <xs:element ref="Grabadora"/>
        </xs:choice>
    </xs:group>
  
    <!--CD/DVD--> 
    <xs:element name="Lectora">
        <xs:complexType>
            <xs:attribute name="Tipo" type="Lect_Grab" />
        </xs:complexType>
    </xs:element>
    
    <xs:element name="Grabadora">
        <xs:complexType>
            <xs:attribute name="Tipo" type="Lect_Grab" />
        </xs:complexType>
    </xs:element>
  
    <xs:simpleType name="Lect_Grab">
        <xs:restriction base="xs:string">
            <xs:enumeration value="CD"/>
            <xs:enumeration value="DVD"/>
        </xs:restriction>
    </xs:simpleType>
    <!--FIN CD/DVD--> 
  
    <!--CONFIG--> 
    <xs:element name="Config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Role" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="OS" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="IP" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="Gateway" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!--NOTAS--> 
    <xs:element name="Notas" type="xs:string"/> 
  
</xs:schema>

=== portoman/DAW_Github/04_Lenguaje de marcas/PreviaExamen2/public_html/rede.xml
<?xml version="1.0" encoding="UTF-8"?>
<Red xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rede_enunciado.xsd">
	<Fecha>01/01/2021</Fecha>
	<Maquina Nombre="Breogan">
		<Info>
			<Tipo>Ordenador de sobremesa</Tipo>
			<Fabricante>HP</Fabricante>
			<Procesador Marca="Intel" Velocidad="2.4">Core i9</Procesador>
			<Memoria>16</Memoria>
			<Disco Tecnologia="SSD" Capacidad="500"/>
			<Grabadora Tipo="DVD"/>
		</Info>
		<Config>
			<OS>Windows 10</OS>
			<IP>192.168.25.30</IP>
			<Gateway>192.168.25.1</Gateway>
		</Config>
		<Notas>Con tarjeta Wifi</Notas>
	</Maquina>
	<Maquina Nombre="Roi">
		<Info>
			<Tipo>Ordenador de sobremesa</Tipo>
			<Fabricante>Dell</Fabricante>
			<Procesador Marca="Intel" Velocidad="3">Core i5</Procesador>
			<Memoria>12</Memoria>
			<Disco Tecnologia="SCSI" Capacidad="500"/>
			<Disco Tecnologia="SCSI" Capacidad="500"/>
			<Disco Tecnologia="SCSI" Capacidad="500"/>
		</Info>
		<Config>
			<Role>Servidor de Active Directory</Role>
			<OS>Windows 2018 Server R2</OS>
			<IP>192.168.25.54</IP>
			<Gateway>192.168.25.1</Gateway>
		</Config>
	</Maquina>
	<Maquina Nombre="Uxia">
		<Info>
			<Tipo>Portátil</Tipo>
			<Memoria>8</Memoria>
			<Disco Capacidad="256"/>
		</Info>
		<Config>
			<OS>Windows 7 SP1</OS>
		</Config>
		<Notas>Conexión por DHCP</Notas>
	</Maquina>
	<Maquina Nombre="Lambre">
		<Info>
			<Tipo>Minipc</Tipo>
			<Disco Capacidad="500"/>
		</Info>
		<Config>
			<OS>Windows 10</OS>
		</Config>
		<Notas>Con tarjeta Wifi</Notas>
	</Maquina>
	<Maquina Nombre="IMP001">
		<Info>
			<Tipo>Impresora Inyección</Tipo>
			<Fabricante>Lexmark</Fabricante>
		</Info>
		<Config>
			<IP>192.168.25.111</IP>
		</Config>
	</Maquina>
	<Maquina Nombre="Sar">
		<Info>
			<Tipo>Ordenador de sobremesa</Tipo>
			<Memoria>4</Memoria>
			<Disco Capacidad="500"/>
		</Info>
		<Config>
			<OS>Windows 7 SP1</OS>
			<IP>192.168.25.65</IP>
			<Gateway>192.168.25.1</Gateway>
		</Config>
	</Maquina>
	<Maquina Nombre="Sarela">
		<Info>
			<Tipo>Ordenador de sobremesa</Tipo>
			<Procesador Marca="AMD" Velocidad="1.4">AMD</Procesador>
			<Memoria>8</Memoria>
			<Disco Capacidad="256"/>
			<Grabadora Tipo="DVD"/>
		</Info>
		<Config>
			<OS>Mandriva 2007</OS>
			<IP>192.168.10.45</IP>
			<Gateway>192.168.10.1</Gateway>
		</Config>
	</Maquina>
	<Maquina Nombre="Verdugo">
		<Info>
			<Tipo>Ordenador de sobremesa</Tipo>
			<Fabricante>Dell</Fabricante>
			<Procesador Marca="Intel" Velocidad="3">AMD</Procesador>
			<Memoria>2</Memoria>
			<Disco Tecnologia="SCSI" Capacidad="500"/>
			<Disco Tecnologia="SCSI" Capacidad="500"/>
			<Grabadora Tipo="CD"/>
		</Info>
		<Config>
			<Role>Servidor LDAP</Role>
			<OS>Windows 2018 Server R2</OS>
			<IP>192.168.25.11</IP>
			<Gateway>192.168.25.1</Gateway>
		</Config>
	</Maquina>
	<Maquina Nombre="Belelle">
		<Info>
			<Tipo>Servidor</Tipo>
			<Fabricante>HP</Fabricante>
			<Procesador Marca="Intel" Velocidad="3">Core i7</Procesador>
			<Memoria>4</Memoria>
			<Disco Tecnologia="SATA" Capacidad="2000"/>
			<Disco Tecnologia="SATA" Capacidad="2000"/>
			<Disco Tecnologia="SATA" Capacidad="2000"/>
		</Info>
		<Config>
			<Role>Servidor de archivos</Role>
			<OS>Ubuntu 18.04 Server</OS>
			<IP>192.168.25.61</IP>
			<IP>192.168.25.62</IP>
			<Gateway>192.168.25.1</Gateway>
		</Config>
	</Maquina>
	<Maquina Nombre="Cadavo">
		<Info>
			<Tipo>Servidor</Tipo>
			<Fabricante>HP</Fabricante>
			<Procesador Marca="Intel" Velocidad="3">Core i7</Procesador>
			<Memoria>4</Memoria>
			<Disco Tecnologia="SSD" Capacidad="500"/>
			<Disco Tecnologia="SATA" Capacidad="500"/>
		</Info>
		<Config>
			<Role>Servidor web</Role>
			<OS>Ubuntu 18.04 Server</OS>
			<IP>192.168.25.74</IP>
			<IP>192.168.25.75</IP>
			<Gateway>192.168.25.1</Gateway>
		</Config>
	</Maquina>
</Red>
